version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    volumes:
      - /app/node_modules
      - ./:/app
    stdin_open: true
    ports:
      - "80:5173"